name: Run Unit Tests and Open Pull Request

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  test-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Run Unit Tests
        run: python unitTests.py


      - name: create pull request
        run: gh pr create -B base_branch -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



