name: Run Unit Tests and Open Pull Request

on:
  push:
    branches:
      - main  

jobs:
  test-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
          
 
          
      - name: Run Unit Tests
        run: python unitTests.py


      - name: create pull request
        run: gh pr create -B base_branch -H branch_to_merge --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



