name: Run Unit Tests and Open Pull Request

on:
  push:
    branches:
      - main  

jobs:
  test-and-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
          
 
          
      - name: Run Unit Tests
        run: python3 unitTests.py


  



